import { BaseSeeder } from '@adonisjs/lucid/seeders';
import TerritoryRepository from '#repositories/territory_repository';
import Territory from '#models/territory';

export default class extends BaseSeeder {
    async run(): Promise<void> {
        const territoryRepository: TerritoryRepository = new TerritoryRepository();

        const territories: { code: string; french: string; english: string; isCoastal: boolean }[] = [
            // ********** North America **********
            { code: 'AL', french: 'Alaska', english: 'Alaska', isCoastal: true },
            { code: 'BC', french: 'Colombie-Britannique', english: 'British Columbia', isCoastal: true },
            { code: 'NT', french: 'Territoires du Nord-Ouest', english: 'Northwest Territories', isCoastal: true },
            { code: 'NU', french: 'Nunavut', english: 'Nunavut', isCoastal: true },
            { code: 'NX', french: 'Ontario du nord', english: 'Northern Ontario', isCoastal: true },
            { code: 'ON', french: 'Ontario du sud', english: 'Southern Ontario', isCoastal: false },
            { code: 'QC', french: 'Québec', english: 'Quebec', isCoastal: true },
            { code: 'FL', french: 'Floride', english: 'Florida', isCoastal: true },
            { code: 'TX', french: 'Texas', english: 'Texas', isCoastal: true },
            { code: 'CA', french: 'Californie', english: 'California', isCoastal: true },
            { code: 'DA', french: 'Dakota', english: 'Dakota', isCoastal: false },
            { code: 'MX', french: 'Mexique', english: 'Mexico', isCoastal: true },
            // ********** South America **********
            { code: 'GT', french: 'Guatemala', english: 'Guatemala', isCoastal: true },
            { code: 'HN', french: 'Honduras', english: 'Honduras', isCoastal: true },
            { code: 'NI', french: 'Nicaragua', english: 'Nicaragua', isCoastal: true },
            { code: 'CR', french: 'Costa Rica', english: 'Costa Rica', isCoastal: true },
            { code: 'PA', french: 'Panama', english: 'Panama', isCoastal: true },
            { code: 'CO', french: 'Colombie', english: 'Colombia', isCoastal: true },
            { code: 'VE', french: 'Vénézuéla', english: 'Venezuela', isCoastal: true },
            { code: 'SR', french: 'Suriname', english: 'Suriname', isCoastal: true },
            { code: 'EC', french: 'Équateur', english: 'Ecuador', isCoastal: true },
            { code: 'PE', french: 'Pérou', english: 'Peru', isCoastal: true },
            { code: 'CL', french: 'Chili', english: 'Chile', isCoastal: true },
            { code: 'AR', french: 'Argentine', english: 'Argentina', isCoastal: true },
            { code: 'UY', french: 'Uruguay', english: 'Uruguay', isCoastal: true },
            { code: 'BR', french: 'Brésil', english: 'Brazil', isCoastal: true },
            { code: 'PY', french: 'Paraguay', english: 'Paraguay', isCoastal: false },
            { code: 'BO', french: 'Bolivie', english: 'Bolivia', isCoastal: false },
            { code: 'FK', french: 'Falkland', english: 'Falkland', isCoastal: true },
            // ********** Caribbean **********
            { code: 'CU', french: 'Cuba', english: 'Cuba', isCoastal: true },
            { code: 'BS', french: 'Bahamas', english: 'Bahamas', isCoastal: true },
            { code: 'HT', french: 'Haı̈ti', english: 'Haiti', isCoastal: true },
            { code: 'JM', french: 'Jamaïque', english: 'Jamaica', isCoastal: true },
            { code: 'PR', french: 'Porto Rico', english: 'Puerto Rico', isCoastal: true },
            { code: 'TT', french: 'Trinité et Tobago', english: 'Trinidad and Tobago', isCoastal: true },
            // ********** Europe **********
            { code: 'AC', french: 'Açores', english: 'Azores', isCoastal: true },
            { code: 'IS', french: 'Islande', english: 'Iceland', isCoastal: true },
            { code: 'SN', french: 'Écosse', english: 'Scotland', isCoastal: true },
            { code: 'IL', french: 'Irlande', english: 'Ireland', isCoastal: true },
            { code: 'GB', french: 'Grande-Bretagne', english: 'Great Britain', isCoastal: true },
            { code: 'NF', french: 'Nord de la France', english: 'Northern France', isCoastal: true },
            { code: 'MF', french: 'France centrale', english: 'Middle France', isCoastal: true },
            { code: 'SF', french: 'Sud de la France', english: 'Southern France', isCoastal: true },
            { code: 'ES', french: 'Espagne', english: 'Spain', isCoastal: true },
            { code: 'PT', french: 'Portugal', english: 'Portugal', isCoastal: true },
            { code: 'BA', french: 'Baléares', english: 'Balearic', isCoastal: true },
            { code: 'SG', french: 'Sardaigne', english: 'Sardinia', isCoastal: true },
            { code: 'IT', french: 'Italie', english: 'Italia', isCoastal: true },
            { code: 'SL', french: 'Sicile', english: 'Sicily', isCoastal: true },
            { code: 'NL', french: 'Pays-Bas', english: 'Netherlands', isCoastal: true },
            { code: 'RH', french: 'Rhénanie', english: 'Rhine', isCoastal: false },
            { code: 'SX', french: 'Saxe', english: 'Saxony', isCoastal: true },
            { code: 'PS', french: 'Prusse', english: 'Prussia', isCoastal: true },
            { code: 'AT', french: 'Autriche', english: 'Austria', isCoastal: true },
            { code: 'RO', french: 'Roumanie', english: 'Romania', isCoastal: true },
            { code: 'BG', french: 'Bulgarie', english: 'Bulgaria', isCoastal: true },
            { code: 'GR', french: 'Grèce', english: 'Greece', isCoastal: true },
            { code: 'DK', french: 'Danemark', english: 'Denmark', isCoastal: true },
            { code: 'NO', french: 'Norvège', english: 'Norway', isCoastal: true },
            { code: 'SE', french: 'Suède', english: 'Sweden', isCoastal: true },
            { code: 'FI', french: 'Finlande', english: 'Finland', isCoastal: true },
            { code: 'UR', french: 'Oural', english: 'Ural', isCoastal: true },
            // ********** Africa **********
            { code: 'CN', french: 'Canaries', english: 'Canaries', isCoastal: true },
            { code: 'CV', french: 'Cap Vert', english: 'Cape Verde', isCoastal: true },
            { code: 'ST', french: 'Sao Tomé et Principe', english: 'Sao Tome and Principe', isCoastal: true },
            { code: 'MA', french: 'Maroc', english: 'Morocco', isCoastal: true },
            { code: 'DZ', french: 'Algérie', english: 'Algeria', isCoastal: true },
            { code: 'TN', french: 'Tunisie', english: 'Tunisia', isCoastal: true },
            { code: 'LY', french: 'Libye', english: 'Libya', isCoastal: true },
            { code: 'EG', french: 'Égypte', english: 'Egypt', isCoastal: true },
            { code: 'MR', french: 'Mauritanie', english: 'Mauritania', isCoastal: true },
            { code: 'GN', french: 'Guinée', english: 'Guinea', isCoastal: true },
            { code: 'ML', french: 'Mali', english: 'Mali', isCoastal: false },
            { code: 'CI', french: 'Côte d’Ivoire', english: 'Côte d’Ivoire', isCoastal: true },
            { code: 'NG', french: 'Nigeria', english: 'Nigeria', isCoastal: true },
            { code: 'NE', french: 'Niger', english: 'Niger', isCoastal: false },
            { code: 'TD', french: 'Tchad', english: 'Chad', isCoastal: false },
            { code: 'SD', french: 'Soudan', english: 'Sudan', isCoastal: true },
            { code: 'CM', french: 'Cameroun', english: 'Cameroon', isCoastal: true },
            { code: 'ET', french: 'Éthiopie', english: 'Ethiopia', isCoastal: false },
            { code: 'SO', french: 'Somalie', english: 'Somalia', isCoastal: true },
            { code: 'KE', french: 'Kenya', english: 'Kenya', isCoastal: true },
            { code: 'CD', french: 'République démocratique du Congo', english: 'Democratic Republic of the Congo', isCoastal: true },
            { code: 'TZ', french: 'Tanzanie', english: 'Tanzania', isCoastal: true },
            { code: 'MZ', french: 'Mozambique', english: 'Mozambique', isCoastal: true },
            { code: 'AO', french: 'Angola', english: 'Angola', isCoastal: true },
            { code: 'NA', french: 'Namibie', english: 'Namibia', isCoastal: true },
            { code: 'ZM', french: 'Zambie', english: 'Zambia', isCoastal: false },
            { code: 'BW', french: 'Botswana', english: 'Botswana', isCoastal: false },
            { code: 'ZA', french: 'Afrique du Sud', english: 'South Africa', isCoastal: true },
            { code: 'MG', french: 'Madagascar', english: 'Madagascar', isCoastal: true },
            { code: 'MU', french: 'Maurice', english: 'Mauritius', isCoastal: true },
            { code: 'KM', french: 'Comores', english: 'Comoros', isCoastal: true },
            { code: 'SC', french: 'Seychelles', english: 'Seychelles', isCoastal: true },
            { code: 'DR', french: 'Socotra', english: 'Socotra', isCoastal: true },
            // ********** Middle East **********
            { code: 'TR', french: 'Turquie', english: 'Turkey', isCoastal: true },
            { code: 'CY', french: 'Chypre', english: 'Cyprus', isCoastal: true },
            { code: 'IQ', french: 'Iraq', english: 'Iraq', isCoastal: true },
            { code: 'SY', french: 'Syrie', english: 'Syria', isCoastal: true },
            { code: 'JO', french: 'Jordanie', english: 'Jordan', isCoastal: true },
            { code: 'SA', french: 'Arabie saoudite', english: 'Saudi Arabia', isCoastal: true },
            { code: 'YE', french: 'Yemen', english: 'Yemen', isCoastal: true },
            { code: 'OM', french: 'Oman', english: 'Oman', isCoastal: true },
            // ********** Asia **********
            { code: 'SW', french: 'Sibérie occidentale', english: 'Western Siberia', isCoastal: false },
            { code: 'CS', french: 'Sibérie centrale', english: 'Central Siberia', isCoastal: false },
            { code: 'SI', french: 'Sibérie orientale', english: 'Eastern Siberia', isCoastal: true },
            { code: 'IR', french: 'Perse', english: 'Persia', isCoastal: true },
            { code: 'AF', french: 'Afghanistan', english: 'Afghanistan', isCoastal: false },
            { code: 'WP', french: 'Pakistan occidental', english: 'Western Pakistan', isCoastal: true },
            { code: 'EP', french: 'Pakistan oriental', english: 'Eastern Pakistan', isCoastal: true },
            { code: 'NK', french: 'Nord du Pakistan', english: 'Northern Pakistan', isCoastal: false },
            { code: 'NP', french: 'Népal', english: 'Nepal', isCoastal: false },
            { code: 'UP', french: 'Uttar Pradesh', english: 'Uttar Pradesh', isCoastal: false },
            { code: 'WI', french: 'Inde occidentale', english: 'Western India', isCoastal: true },
            { code: 'MI', french: 'Inde centrale', english: 'Central India', isCoastal: true },
            { code: 'EI', french: 'Inde orientale', english: 'Eastern India', isCoastal: true },
            { code: 'LK', french: 'Sri Lanka', english: 'Sri Lanka', isCoastal: true },
            { code: 'MV', french: 'Maldives', english: 'Maldives', isCoastal: true },
            { code: 'BD', french: 'Bangladesh', english: 'Bangladesh', isCoastal: true },
            { code: 'BT', french: 'Bhoutan', english: 'Bhutan', isCoastal: false },
            { code: 'MM', french: 'Myanmar', english: 'Myanmar', isCoastal: true },
            { code: 'TH', french: 'Thailand', english: 'Thailand', isCoastal: true },
            { code: 'KH', french: 'Cambodge', english: 'Cambodia', isCoastal: true },
            { code: 'VN', french: 'Vietnam', english: 'Vietnam', isCoastal: true },
            { code: 'MC', french: 'Mandchourie', english: 'Manchuria', isCoastal: true },
            { code: 'KO', french: 'Corée', english: 'Korea', isCoastal: true },
            { code: 'MN', french: 'Mongolie', english: 'Mongolia', isCoastal: false },
            { code: 'TB', french: 'Tibet', english: 'Tibet', isCoastal: false },
            { code: 'SH', french: 'Shaanxi', english: 'Shaanxi', isCoastal: false },
            { code: 'YN', french: 'Yunnan', english: 'Yunnan', isCoastal: true },
            { code: 'SZ', french: 'Shandong', english: 'Shandong', isCoastal: true },
            { code: 'TW', french: 'Taiwan', english: 'Taiwan', isCoastal: true },
            { code: 'KI', french: 'Îles Komandorski', english: 'Komandorski Islands', isCoastal: true },
            { code: 'HK', french: 'Hokkaido', english: 'Hokkaido', isCoastal: true },
            { code: 'HS', french: 'Honshu', english: 'Honshu', isCoastal: true },
            { code: 'KU', french: 'Kyushu', english: 'Kyushu', isCoastal: true },
            // ********** Oceania **********
            { code: 'PH', french: 'Philippines', english: 'Philippines', isCoastal: true },
            { code: 'SM', french: 'Sumatra', english: 'Sumatra', isCoastal: true },
            { code: 'JV', french: 'Java', english: 'Java', isCoastal: true },
            { code: 'BE', french: 'Bornéo', english: 'Borneo', isCoastal: true },
            { code: 'SS', french: 'Sulawesi', english: 'Sulawesi', isCoastal: true },
            { code: 'PG', french: 'Papouasie', english: 'Papua', isCoastal: true },
            { code: 'SB', french: 'Îles Salomon', english: 'Solomon Islands', isCoastal: true },
            { code: 'VU', french: 'Vanuatu', english: 'Vanuatu', isCoastal: true },
            { code: 'NZ', french: 'Nouvelle-Zélande', english: 'New Zealand', isCoastal: true },
            { code: 'WA', french: 'Australie Occidentale', english: 'Western Australia', isCoastal: true },
            { code: 'AN', french: 'Territoire du nord', english: 'Northern Territory', isCoastal: true },
            { code: 'QL', french: 'Queensland', english: 'Queensland', isCoastal: true },
            { code: 'NS', french: 'Nouvelle Galle du Sud', english: 'New South Wales', isCoastal: true },
        ];

        for (const territory of territories) {
            if (!(await territoryRepository.findOneBy({ code: territory.code }))) {
                await Territory.create({
                    frenchName: territory.french,
                    englishName: territory.english,
                    code: territory.code,
                    isCoastal: territory.isCoastal,
                });
                console.log(`Territory ${territory.code} created`);
            } else {
                console.log(`Territory ${territory.code} already exists`);
            }
        }
    }
}
