services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: colonizadar_back
        restart: always
        env_file: back/.env
        working_dir: /app/back
        depends_on:
            - db
        networks:
            - colonizadar_back
        volumes:
            - ./back:/app/back
            - /app/back/node_modules
        environment:
            VIRTUAL_HOST: api.colonizadar.fr
            LETSENCRYPT_HOST: api.colonizadar.fr
            LETSENCRYPT_EMAIL: paul.lecuisinier@gmail.com

    db:
        image: postgres:15
        container_name: colonizadar_db
        restart: always
        environment:
            POSTGRES_DB: colonizadar
            POSTGRES_USER: superadmin
            POSTGRES_PASSWORD: xxx
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            colonizadar_back:
                aliases:
                    - db

    adminer:
        image: ghcr.io/shyim/adminerevo:latest
        container_name: colonizadar_adminer
        restart: always
        networks:
            - colonizadar_back
        depends_on:
            - db
        environment:
            VIRTUAL_HOST: db.colonizadar.fr
            LETSENCRYPT_HOST: db.colonizadar.fr
            LETSENCRYPT_EMAIL: paul.lecuisinier@gmail.com

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: colonizadar_proxy
        restart: always
        environment:
            VIRTUAL_HOST: api.colonizadar.fr, db.colonizadar.fr
            LETSENCRYPT_HOST: api.colonizadar.fr, db.colonizadar.fr
            LETSENCRYPT_EMAIL: paul.lecuisinier@gmail.com
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs:ro
            - ./vhost.d:/etc/nginx/vhost.d
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - colonizadar_back

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: colonizadar_ssl
        restart: always
        environment:
            NGINX_PROXY_CONTAINER: colonizadar_proxy
            LETSENCRYPT_HOST: api.colonizadar.fr, db.colonizadar.fr
            LETSENCRYPT_EMAIL: paul.lecuisinier@gmail.com
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certs:/etc/nginx/certs
            - ./vhost.d:/etc/nginx/vhost.d
        depends_on:
            - nginx-proxy
        networks:
            - colonizadar_back

volumes:
    postgres_data:

networks:
    colonizadar_back:
        driver: bridge
