services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: colonizadar_back
        restart: always
        env_file: back/.env
        working_dir: /app/back
        depends_on:
            - postgres
        ports:
            - "3333:3333"
        networks:
            - colonizadar_back
        volumes:
            - ./back:/app/back
            - /app/back/node_modules

    postgres:
        image: postgres:15
        container_name: colonizadar_postgres
        restart: always
        environment:
            POSTGRES_DB: colonizadar
            POSTGRES_USER: superadmin
            POSTGRES_PASSWORD: xxx
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./dev:/docker-entrypoint-initdb.d
        networks:
            - colonizadar_back

    nginx:
        image: nginx:latest
        container_name: colonizadar_nginx
        restart: always
        depends_on:
            - app
            - postgres
            - php
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - colonizadar_back
        extra_hosts:
            - "adminneo.colonizadar.fr:127.0.0.1"
            - "api.colonizadar.fr:127.0.0.1"
            - "colonizadar.fr:127.0.0.1"

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: colonizadar_adminneo
        volumes:
            - .:/var/www/html
        networks:
            - colonizadar_back

volumes:
    postgres_data:

networks:
    colonizadar_back:
        driver: bridge
