services:
    backend:
        build:
            context: .
            dockerfile: ./Dockerfile.back
        container_name: back
        restart: always
        env_file: ./back/.env
        working_dir: /app
        ports:
            - "${PORT:-3333}:3333"
        volumes:
            - ./back/static:/app/static
        depends_on:
            - db
            - redis

    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile.front
        container_name: front
        restart: always
        env_file: ./front/.env
        ports:
            - "4173:4173"
        depends_on:
            - backend
