version: '3.8'

services:
    db:
        image: postgres:15
        container_name: colonizadar_db
        restart: always
        environment:
            POSTGRES_DB: colonizadar
            POSTGRES_USER: superadmin
            POSTGRES_PASSWORD: xxx
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build:
            context: ./back
        container_name: colonizadar_backend
        restart: always
        env_file: ./back/.env
        working_dir: /app
        volumes:
            - ./back:/app
            - /app/node_modules
        ports:
            - "3333:3333"
        depends_on:
            - db

    frontend:
        build:
            context: ./front
        container_name: colonizadar_frontend
        restart: always
        env_file: ./front/.env
        volumes:
            - ./front:/app
        ports:
            - "5173:5173"
        depends_on:
            - backend

    adminer:
        image: ghcr.io/shyim/adminerevo:latest
        container_name: colonizadar_adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - db

volumes:
    postgres_data:
