# Dockerfile.back
FROM node:22

# Create app directory
WORKDIR /app

# Install dependencies
COPY back/package*.json ./
RUN npm install --omit=dev

# Copy application code
COPY back /app

# Compile AdonisJS app
RUN npm run build

# Expose port
EXPOSE 3333

# Run as non-root
USER node

# Start server
CMD ["node", "build/server.js"]
