# Dockerfile.front

# Build stage
FROM node:22 AS builder

WORKDIR /app

COPY front/package*.json ./
RUN npm install

COPY front /app
RUN npm run build

# Serve stage
FROM node:22-slim

WORKDIR /app

# Install lightweight static server
RUN npm install -g serve

# Copy build output from previous stage
COPY --from=builder /app/build ./build

EXPOSE 4173

CMD ["serve", "-s", "build", "-l", "4173"]
